apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        run: wisecow
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: "wisecow:latest"
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4499
        env:
        - name: "TLS_CERT_FILE"
          value: "/etc/tls/tls.crt"
        - name: "TLS_KEY_FILE"
          value: "/etc/tls/tls.key"
        volumeMounts:
        - name: tls-certs
          mountPath: "/etc/tls"
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: wisecow-tls
