apiVersion: v1
kind: Service
metadata:
  name: wisecow
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wisecow
  ports:
  - name: http
    port: 30000
    targetPort: 4499
    nodePort: 30000