apiVersion: v1
kind: Service
metadata:
  name: wisecow
  namespace: default
spec:
  selector:
    app: wisecow
  ports:
  - name: http
    port: 4499
    targetPort: 4499
  type: LoadBalancer
  externalIPs:
    - 192.168.1.145