apiVersion: v1
kind: Service
metadata:
  name: wisecow
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wisecow
  ports:
  - name: https
    port: 4499
    targetPort: 4499
    # nodePort: 30000