name: CI/CD
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t thissudip/wisecow:0.0.1 .
      - name: Push Docker Image
        run: docker push thissudip/wisecow:0.0.1
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          version: 'latest'
          installKubectl: true
      - name: Set Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml