name: CI/CD of Wisecow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Wisecow on Minikube Cluster using Github Actions via Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Generate TLS Certificates
        run: |
          MINIKUBE_IP=$(minikube ip)
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=$MINIKUBE_IP"
      - name: Create Kubernetes Secret
        run: |
          kubectl create secret tls wisecow-tls --cert=tls.crt --key=tls.key
      - name: Build the docker image
        run: |
            export SHELL=/bin/bash
            eval $(minikube -p minikube docker-env)
            docker build -t wisecow:latest .
            echo -n "verifying images:"
            docker images
            docker run -d -p 4499:4499 wisecow:latest
      - name: Deploy to minikube
        run: |
            kubectl apply -f ./kubernetes/deployment.yaml
            kubectl apply -f ./kubernetes/service.yaml
      - name: Verify deployment
        run: |
            kubectl get pods
            kubectl get svc
      - name: Test service URLs
        run: |
            minikube service list
            kubectl describe service wisecow